controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# login:
#     path: /api/login
#     controller: lexik_jwt_authentication.controller.login
#     methods: ['POST']
